### PR TITLE
Add ROS2 Release Nightlies table

### PR DESCRIPTION
**Pull request by mjcarroll**
This adds the isolated nightly release builds in a table.

This is helpful for monitoring the status of `foxy` against `focal` as well as regressions in already-released distributions.

### CODE REVIEW

**Comment by prajakta-gokhale** [comment]
Thanks for the patch, @mjcarroll. This is a board used by the AWS Oncall to keep track of builds that are actively monitored by the team. Is the expectation here for oncall to monitor these nightly release builds and report failures in failing repos?

**Comment by mjcarroll** [comment]
I think it's a useful secondary view of the status of the buildfarm.  

As we discussed in the triage meeting this week, ci.ros2.org doesn't test each rmw implementation in isolation like build.ros2.org does.  Additionally, ci.ros2.org hasn't switched over to `focal` so these could be considered preliminary builds for that configuration with `foxy`

I'll leave it up to you if it's useful to incorporate in the board.  If not, I'll probably keep it alive in my fork because I think it would be personally useful.

**Comment by thomas-moulard** [comment]
I think that's useful! I'll let other people chime in but I think we should merge this.

**Comment by prajakta-gokhale** [comment]
I agree, I think this is useful to us as well.

**Comment by dabonnie** [comment]
Agreed! Ship it!

**Pull request merged**
