### PR TITLE
Update monthly-report-for-oncall.yml

### PR DESCRIPTION
**Pull request by dabonnie**
Rename generated report files to avoid confusion

### CODE REVIEW

**Comment by zmichaels11** [comment]
This work requires names of reports to be configurable.
Opened issue on https://github.com/ros-security/github-contribution-report-generator/issues/8

**Comment by zmichaels11** [comment]
This change might be ready now that the [required work was merged](https://github.com/ros-security/github-contribution-report-generator/pull/12).

**Comment by zmichaels11** [comment]
There's an error:
```bash
##[error]Path does not exist /home/runner/work/aws-oncall/aws-oncall/monthly-report.html
```

**Comment by piraka9011** [comment]
Might just need a version bump to the report generator.

**Pull request merged**
